### ISSUE TITLE
Angelica Dynamic Lights Compatibility

### ISSUE THREAD

**Issue by DarianLStephens** [tesseract4d/OffhandLights#1]
The mod doesn't seem to work with Angelica's dynamic lights.
It would be appreciated if it could, as that's what's included in GTNH.

**Comment by tesseract4d** [comment]
Ok,I will check it later

**Comment by tesseract4d** [comment]
Does Angelica support dynamic lights?I didn't find dynamic lights option.

**Comment by DarianLStephens** [comment]
It does!
You need to enable the module in the 'config/angelica-modules.cfg' file, otherwise the option in video settings won't show up.

**Comment by tesseract4d** [comment]
Done.I renamed the mod since its compatibility.
