### ISSUE TITLE
添加对Smooth Entity Light的支持

### ISSUE THREAD

**Issue by Omgise** [Tesseract4D/OffhandLights#2]
https://github.com/DrParadox7/Smooth-Entity-Light

**Comment by tesseract4d** [comment]
这个模组貌似根本不能用

**Comment by tesseract4d** [comment]
你没试过吗

**Comment by Omgise** [comment]
试过了，可以用的

**Comment by Omgise** [comment]
等下我录个视频给你看看

**Comment by Omgise** [comment]
https://www.dropbox.com/scl/fi/mkpawbcw4c4njlwfdhlg6/2024-06-04-22-47-53.mkv?rlkey=raj0wq2bof5ke4pjjd8286w9m&st=tuiwi0p2&dl=0

**Comment by tesseract4d** [comment]
![image](https://github.com/tesseract4d/OffhandLights/assets/55395193/9ac41370-c4aa-4f39-a5f6-43e7a4095a16)
