### ISSUE TITLE
AtomicStryker's Dynamic light mod

### ISSUE THREAD

**Issue by rockrevenchy** [Tesseract4D/OffhandLights#4]
In my case I can neither use angelic nor optifine for compatibility reasons, thus I use this mod which is unfortunately unsupported :(

Thx for maintaining 1.7.10 with newer mods also :D

https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/tree/1.7.10/DynamicLights

https://www.curseforge.com/minecraft/mc-mods/dynamic-lights

**Comment by tesseract4d** [comment]
I cannot transform AtomicStryker Dynamic Lights classes somehow,maybe I should try mixin later
