### ISSUE TITLE
Doesn't work with Backhand mod 

### ISSUE THREAD

**Issue by brandyyn** [tesseract4d/OffhandLights#5]
Main hand:
![image](https://github.com/tesseract4d/OffhandLights/assets/11356565/d4af2b95-5a4b-4d5a-8e3b-73b7e399c6b5)

Backhand:
![image](https://github.com/tesseract4d/OffhandLights/assets/11356565/699773a2-4e5e-4db0-a6e4-e5f5d16d1412)

it DOES work with battlegear, but it doesn't work with backhand like you claim in the description

**Comment by rockrevenchy** [comment]
oh you know what, my [issue](https://github.com/tesseract4d/OffhandLights/issues/4) might be related to this, I do use backhand + atomicstryker dynamic light

**Comment by brandyyn** [comment]
> oh you know what, my [issue](https://github.com/tesseract4d/OffhandLights/issues/4) might be related to this, I do use backhand + atomicstryker dynamic light

yo, the new version of angelica dynamic lights supports backhand and battlegear as of today. you'll have to build it yourself tho, or i can send a jar

**Comment by tesseract4d** [comment]
What version of Backhand you two uses?

**Comment by tesseract4d** [comment]
The guy,c0508383,moved mods.battlegear2.api.core.InventoryPlayerBattle to xonin.backhand.api.core.InventoryPlayerBackhand in newer version so old code doesnot work.

**Comment by tesseract4d** [comment]
Every fork of Battlegear2 I konw renamed their package/class/method name.Not a big problem but annoying.

**Comment by tesseract4d** [comment]
I will fix it later.
