### ISSUE TITLE
Right Proper Lighting Engine不兼容

### ISSUE THREAD

**Issue by huihiuhuai** [Tesseract4D/OffhandLights#7]
![image](https://github.com/user-attachments/assets/d9a9e84d-b3a7-435e-a393-2d4b38a1d452)
![image](https://github.com/user-attachments/assets/5a4d072b-e9dd-4b3c-b930-4a35e68e9aa0)
![image](https://github.com/user-attachments/assets/fce6c6d9-1aa0-4188-a198-3c1908c57f0f)

**Comment by Tesseract4D** [comment]
怎么前置这么多😡

**Comment by Tesseract4D** [comment]
这哪来的动态光源

**Comment by huihiuhuai** [comment]
optifine 的

**Comment by Tesseract4D** [comment]
已兼容
https://modrinth.com/mod/offhandlights/version/1.4.2

**Comment by brandyyn** [comment]
@Tesseract4D does not work with the latest falsetweaks/rple/optifine + backhand.

**Comment by brandyyn** [comment]
![image](https://github.com/user-attachments/assets/312c9f36-2dfc-46ee-8c48-352e95390908)
![image](https://github.com/user-attachments/assets/0be438c1-f4d6-4d45-a78b-907ba3c05398)
