### ISSUE TITLE
crash with angelica

### ISSUE THREAD

**Issue by iamsoNewBee** [Tesseract4D/OffhandLights#8]
[crash-2024-10-31_23.19.04-client.txt](https://github.com/user-attachments/files/17589589/crash-2024-10-31_23.19.04-client.txt)

**Comment by huihiuhuai** [comment]
angelica 包含副手光源支持的吧

> [crash-2024-10-31_23.19.04-client.txt](https://github.com/user-attachments/files/17589589/crash-2024-10-31_23.19.04-client.txt)

**Comment by iamsoNewBee** [comment]
啊？我以前一直是一块用的

**Comment by Tesseract4D** [comment]
已修复

**Comment by huihiuhuai** [comment]
https://github.com/GTNewHorizons/Angelica/pull/534 angelica 对 backhand 的动态光源兼容。开启光源angelica 自动禁用动态光源所以没效果
