### ISSUE TITLE
Crash with latest RPLE

### ISSUE THREAD

**Issue by DarianLStephens** [Tesseract4D/OffhandLights#9]
With [Right Proper Lighting Engine](https://modrinth.com/mod/rple) installed, having anything in your offhand will crash the game when the player renders.
This includes just going in to third-person.
There's also no dynamic light visible. This is using FalseTweaks' dynamic light.

I realize now that this mod may simply have never had compatibility, but it would be great to see!

**Comment by Tesseract4D** [comment]
https://github.com/FalsePattern/FalseTweaks/issues/198

**Comment by DarianLStephens** [comment]
I'm looking forward to the Offhand Lights update!

**Comment by brandyyn** [comment]
> [FalsePattern/FalseTweaks#198](https://github.com/FalsePattern/FalseTweaks/issues/198)

offhand lights are still not visible tho with RPLE

**Comment by Tesseract4D** [comment]
![2024-11-16_13 18 34](https://github.com/user-attachments/assets/a4578769-5140-4745-bb16-7a7ef9f97c77)
Fixed in [1.4.4](https://modrinth.com/mod/offhandlights/version/1.4.4).
